// Recibe el nombre del actor (sin extensión) y retorna la ruta completa de la imagen si existe
// Actualiza este array con todas las rutas de imágenes de actores
const actorImageRoutes = [
  '/imagenesMovie/background/actors/bambi/felixSalten.webp',
  '/imagenesMovie/background/actors/bambi/jeanPierreBailly.webp',
  '/imagenesMovie/background/actors/bambi/laurentCharbonnier.webp',
  '/imagenesMovie/background/actors/bambi/laurentPerezDelMar.webp',
  '/imagenesMovie/background/actors/bambi/michelFessler.webp',
  '/imagenesMovie/background/actors/bambi/myleneFarmer.webp',
  '/imagenesMovie/background/actors/bambi/reginaldDeGuillebon.webp',
  '/imagenesMovie/background/actors/bambi/stephaneMilliere.webp',

  '/imagenesMovie/background/actors/blancaNieves/andrewBurnap.webp',
  '/imagenesMovie/background/actors/blancaNieves/ansuKabia.webp',
  '/imagenesMovie/background/actors/blancaNieves/colinMichaelCarmichael.webp',
  '/imagenesMovie/background/actors/blancaNieves/emiliaFaucher.webp',
  '/imagenesMovie/background/actors/blancaNieves/galGadot.webp',
  '/imagenesMovie/background/actors/blancaNieves/georgeAppleby.webp',
  '/imagenesMovie/background/actors/blancaNieves/hadleyFraser.webp',
  '/imagenesMovie/background/actors/blancaNieves/jeremySwift.webp',
  '/imagenesMovie/background/actors/blancaNieves/lorenaAndrea.webp',
  '/imagenesMovie/background/actors/blancaNieves/rachelZegler.webp',

  '/imagenesMovie/background/actors/destinoFinal/andrewTinpoLee.webp',
  '/imagenesMovie/background/actors/destinoFinal/annaLore.webp',
  '/imagenesMovie/background/actors/destinoFinal/brecBassinger.webp',
  '/imagenesMovie/background/actors/destinoFinal/gabrielleRose.webp',
  '/imagenesMovie/background/actors/destinoFinal/kaitlynSantaJuana.webp',
  '/imagenesMovie/background/actors/destinoFinal/owenPatrickJoyner.webp',
  '/imagenesMovie/background/actors/destinoFinal/richardHarmon.webp',
  '/imagenesMovie/background/actors/destinoFinal/ryaKihlstedt.webp',
  '/imagenesMovie/background/actors/destinoFinal/teoBriones.webp',
  '/imagenesMovie/background/actors/destinoFinal/tonyTodd.webp',

  '/imagenesMovie/background/actors/extraterritorial/annabelleMandeng.webp',
  '/imagenesMovie/background/actors/extraterritorial/dougrayScott.webp',
  '/imagenesMovie/background/actors/extraterritorial/emanuelFellmer.webp',
  '/imagenesMovie/background/actors/extraterritorial/jeanneGoursaud.webp',
  '/imagenesMovie/background/actors/extraterritorial/kayodeAkinyemi.webp',
  '/imagenesMovie/background/actors/extraterritorial/krisSaddler.webp',
  '/imagenesMovie/background/actors/extraterritorial/leraAbova.webp',
  '/imagenesMovie/background/actors/extraterritorial/ninaLiu.webp',
  '/imagenesMovie/background/actors/extraterritorial/samiaHofmann.webp',
  '/imagenesMovie/background/actors/extraterritorial/susanneMichel.webp',

  '/imagenesMovie/background/actors/laBalaPerdida3/albanLenoir.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/anneSerra.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/charlesMorillon.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/gerardLanvin.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/julieTedesco.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/nicolasDuvauchelle.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/pascaleArbillot.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/ramzyBedia.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/sebastienLalanne.webp',
  '/imagenesMovie/background/actors/laBalaPerdida3/stefiCelma.webp',

  '/imagenesMovie/background/actors/misionImposible/esaiMorales.webp',
  '/imagenesMovie/background/actors/misionImposible/hayleyAtwell.webp',
  '/imagenesMovie/background/actors/misionImposible/henryCzerny.webp',
  '/imagenesMovie/background/actors/misionImposible/holtMcCallany.webp',
  '/imagenesMovie/background/actors/misionImposible/janetMcTeer.webp',
  '/imagenesMovie/background/actors/misionImposible/nickOfferman.webp',
  '/imagenesMovie/background/actors/misionImposible/pomKlementieff.webp',
  '/imagenesMovie/background/actors/misionImposible/simonPegg.webp',
  '/imagenesMovie/background/actors/misionImposible/tomCruise.webp',
  '/imagenesMovie/background/actors/misionImposible/vingRhames.webp',

  '/imagenesMovie/background/actors/thunderbolts/chrisBauer.webp',
  '/imagenesMovie/background/actors/thunderbolts/davidHarbour.webp',
  '/imagenesMovie/background/actors/thunderbolts/florencePugh.webp',
  '/imagenesMovie/background/actors/thunderbolts/geraldineViswanathan.webp',
  '/imagenesMovie/background/actors/thunderbolts/hannahJohn-Kamen.webp',
  '/imagenesMovie/background/actors/thunderbolts/juliaLouis-Dreyfus.webp',
  '/imagenesMovie/background/actors/thunderbolts/lewisPullman.webp',
  '/imagenesMovie/background/actors/thunderbolts/sebastianStan.webp',
  '/imagenesMovie/background/actors/thunderbolts/wendellPierce.webp',
  '/imagenesMovie/background/actors/thunderbolts/wyattRussell.webp',

  '/imagenesMovie/background/actors/tiempoDeGuerra/adainBradley.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/cosmoJarvis.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/dPharaohWoon-A-Tai.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/evanHoltzman.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/finnBennett.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/kitConnor.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/michaelGandolfini.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/noahCentineo.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/taylorJohnSmith.webp',
  '/imagenesMovie/background/actors/tiempoDeGuerra/willPoulter.webp',

  '/imagenesMovie/background/actors/tinSoldier/eireFarrell.webp',
  '/imagenesMovie/background/actors/tinSoldier/jamieFoxx.webp',
  '/imagenesMovie/background/actors/tinSoldier/johnLeguizamo.webp',
  '/imagenesMovie/background/actors/tinSoldier/noraArnezeder.webp',
  '/imagenesMovie/background/actors/tinSoldier/ritaOra.webp',
  '/imagenesMovie/background/actors/tinSoldier/robertDeNiro.webp',
  '/imagenesMovie/background/actors/tinSoldier/saidTaghmaoui.webp',
  '/imagenesMovie/background/actors/tinSoldier/scottEastwood.webp',
  '/imagenesMovie/background/actors/tinSoldier/shamierAnderson.webp',
  '/imagenesMovie/background/actors/tinSoldier/yulVazquez.webp',
  
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/bramScottBreheny.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/danielleBrooks.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/emmaMyers.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/jackBlack.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/jasonMomoa.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/jenniferCoolidge.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/markWright.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/moanaWilliams.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/sebastianEugeneHansen.webp',
  '/imagenesMovie/background/actors/unaPeliculaDeMinecraft/yvetteParsons.webp',

];

export function searchActorImageRoute(actorName) {
  // Busca la ruta que termina con /{actorName}.webp
  return actorImageRoutes.find(route => {
    const routeName = route.split('/').pop().replace('.webp', '');
    return routeName === actorName;
  }) || null;
}
